[package]
name = "PiBot"
version = "0.1.0"
edition = "2021"

[dependencies]
gemini-rs = "*"
lazy_static = "1.5.0"
serenity = "*"
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread"] }
